.PHONY: clean All

All:
	@echo "----------Building project:[ LAB1 - Debug ]----------"
	@cd "LAB1" && "$(MAKE)" -f  "LAB1.mk"
clean:
	@echo "----------Cleaning project:[ LAB1 - Debug ]----------"
	@cd "LAB1" && "$(MAKE)" -f  "LAB1.mk" clean
