.PHONY: clean All

All:
	@echo "----------Building project:[ LAB_2 - Debug ]----------"
	@cd "LAB_2" && "$(MAKE)" -f  "LAB_2.mk"
clean:
	@echo "----------Cleaning project:[ LAB_2 - Debug ]----------"
	@cd "LAB_2" && "$(MAKE)" -f  "LAB_2.mk" clean
